# -*- coding: utf-8 -*-
"""
110项老吴大师占卜技法全量自动化测试与校准规范定义
- 严格对接 laowu-master 实际返回键结构与占卜逻辑契约
- 涵盖东方术数、西洋古典占星、七政四余、吠陀印占、高阶星限、
  易经六爻、十大神数典籍、通胜择吉、民间杂占与正史天文数据库。
"""

TECHNIQUES_110 = [
    # ==========================================
    # 一、东方术数与正统三式 (9项)
    # ==========================================
    {
        "id": 1,
        "tool": "bazi",
        "category": "东方术数与三式",
        "name_zh": "高精八字四柱干支排盘",
        "input": {"date": "2026-09-30", "time": "14:00:00", "gender": 1},
        "description": "太阳黄经平黄经秒级节气交节推算四柱八字干支",
        "verify_key": "year_pillar",
        "check_db": False,
    },
    {
        "id": 2,
        "tool": "bazi_inverse",
        "category": "东方术数与三式",
        "name_zh": "八字四柱干支逆推公历生辰",
        "input": {"year_gz": "丙午", "month_gz": "丁酉", "day_gz": "丁未", "hour_gz": "丁未", "start_year": 1900, "end_year": 2100},
        "description": "给定四柱反解真实公历历元与节气交界",
        "verify_key": "candidates",
        "check_db": False,
    },
    {
        "id": 3,
        "tool": "ziwei",
        "category": "东方术数与三式",
        "name_zh": "紫微斗数安星命盘与十二宫",
        "input": {"year": 2026, "month": 9, "day": 30, "hour": 14, "gender": 1},
        "description": "定命宫身宫、定五行局、起十四主星与诸吉凶星曜",
        "verify_key": "ming_palace_zhi",
        "check_db": False,
    },
    {
        "id": 4,
        "tool": "qimen",
        "category": "东方术数与三式",
        "name_zh": "奇门遁甲转盘时家奇门局",
        "input": {"year": 2026, "month": 9, "day": 30, "hour": 14, "minute": 0, "second": 0},
        "description": "九宫八门九星八神、值符值使与三奇六仪",
        "verify_key": "leader_door",
        "check_db": False,
    },
    {
        "id": 5,
        "tool": "taiyi",
        "category": "东方术数与三式",
        "name_zh": "太乙神数天目客算主算局",
        "input": {"year": 2026, "month": 9, "day": 30, "hour": 14, "style": 3},
        "description": "太乙七十二局立成、主计客计与十六神落宫",
        "verify_key": "kook_name",
        "check_db": False,
    },
    {
        "id": 6,
        "tool": "jinkou",
        "category": "东方术数与三式",
        "name_zh": "大六壬金口诀四位推命",
        "input": {"hour": 14, "day_gan": "甲", "hour_zhi": 2, "yue_jiang": 8, "di_fen": 2},
        "description": "人元、贵神、将神、地分四位立式与五动生克",
        "verify_key": "ren_yuan",
        "check_db": False,
    },
    {
        "id": 7,
        "tool": "liureng",
        "category": "东方术数与三式",
        "name_zh": "大六壬正宗三传四课九宗门",
        "input": {"hour": 14, "day_gan": "甲", "day_zhi": 0, "yue_jiang": 8, "zhan_shi": 6},
        "description": "月将加时起天地盘、贼克比用涉害等发端",
        "verify_key": "san_chuan",
        "check_db": False,
    },
    {
        "id": 8,
        "tool": "liureng_runyear",
        "category": "东方术数与三式",
        "name_zh": "大六壬男女行年神煞推运",
        "input": {"age": 30.0, "gender": 1},
        "description": "男顺女逆起行年神煞分布列表",
        "verify_key": None,  # 返回 list
        "check_db": False,
    },
    {
        "id": 9,
        "tool": "sanshiunited",
        "category": "东方术数与三式",
        "name_zh": "太乙奇门六壬三式合一",
        "input": {"year": 2026, "month": 9, "day": 30, "hour": 14},
        "description": "天地人三才综合枢纽盘联动",
        "verify_key": "taiyi",
        "check_db": False,
    },

    # ==========================================
    # 二、西洋占星与古典流派 (19项)
    # ==========================================
    {
        "id": 10,
        "tool": "chart",
        "category": "西洋古典与现代占星",
        "name_zh": "本命占星盘 (Natal Chart) 与萨比恩象征",
        "input": {"date": "2026-09-30", "time": "14:00:00", "lat": 31.23, "lon": 121.47},
        "description": "VSOP87 现代高精行星真视黄经、宫位与萨比恩度数象征",
        "verify_key": "ascendant",
        "check_db": True,
        "db_field": "sun_sabian_symbol",
    },
    {
        "id": 11,
        "tool": "transit",
        "category": "西洋古典与现代占星",
        "name_zh": "流年行运盘 (Transit Chart)",
        "input": {"date": "2026-09-30", "time": "14:00:00", "lat": 31.23, "lon": 121.47},
        "description": "行运行星与本命盘即时交角与入相判定",
        "verify_key": "planets",
        "check_db": False,
    },
    {
        "id": 12,
        "tool": "synastry",
        "category": "西洋古典与现代占星",
        "name_zh": "双人占星比较合盘 (Synastry)",
        "input": {"date": "2026-09-30", "time": "14:00:00", "lat": 31.23, "lon": 121.47},
        "description": "双命盘天体互落宫位与相位互动矩阵",
        "verify_key": "houses",
        "check_db": False,
    },
    {
        "id": 13,
        "tool": "composite_chart",
        "category": "西洋古典与现代占星",
        "name_zh": "双人组合中点盘 (Composite Chart)",
        "input": {"date": "2026-09-30", "time": "14:00:00", "lat": 31.23, "lon": 121.47},
        "description": "计算两个命盘所有行星与交点的数学中点构成新盘",
        "verify_key": "planets",
        "check_db": False,
    },
    {
        "id": 14,
        "tool": "davison",
        "category": "西洋古典与现代占星",
        "name_zh": "戴维森时空关系盘 (Davison Relationship)",
        "input": {"date": "2026-09-30", "time": "14:00:00", "lat": 31.23, "lon": 121.47},
        "description": "时间和地理坐标双重中点独立排盘",
        "verify_key": "ascendant",
        "check_db": False,
    },
    {
        "id": 15,
        "tool": "chart12",
        "category": "西洋古典与现代占星",
        "name_zh": "十二分盘 (Dwadasamsa) 微黄道展开",
        "input": {"date": "2026-09-30", "time": "14:00:00", "lat": 31.23, "lon": 121.47},
        "description": "度数乘12阶展开映射潜意识深层结构",
        "verify_key": "planets",
        "check_db": False,
    },
    {
        "id": 16,
        "tool": "chart13",
        "category": "西洋古典与现代占星",
        "name_zh": "十三分扩展盘与蛇夫座维度拓扑",
        "input": {"date": "2026-09-30", "time": "14:00:00", "lat": 31.23, "lon": 121.47},
        "description": "十三谐波展开与蛇夫座维度拓扑分析",
        "verify_key": "planets",
        "check_db": False,
    },
    {
        "id": 17,
        "tool": "relocation",
        "category": "西洋古典与现代占星",
        "name_zh": "重置地理星盘 (Relocation Chart)",
        "input": {"date": "2026-09-30", "time": "14:00:00", "target_lat": 39.9, "target_lon": 116.4},
        "description": "迁移目标地经纬度重算上升ASC、天顶MC与十二宫位",
        "verify_key": "target_lat",
        "check_db": False,
    },
    {
        "id": 18,
        "tool": "acg",
        "category": "西洋古典与现代占星",
        "name_zh": "占星制图天球投影 (AstroCartoGraphy)",
        "input": {"date": "2026-09-30", "time": "14:00:00"},
        "description": "计算全球各行星上升/天顶/下降/天底投射地理经线",
        "verify_key": "lines_count",
        "check_db": False,
    },
    {
        "id": 19,
        "tool": "solarreturn",
        "category": "西洋古典与现代占星",
        "name_zh": "太阳返照推运盘 (Solar Return)",
        "input": {"date": "2026-09-30", "time": "14:00:00", "target_year": 2027, "lat": 31.23, "lon": 121.47},
        "description": "推算太阳重返出生精确黄经时刻构建年运盘",
        "verify_key": "return_sun_lon",
        "check_db": False,
    },
    {
        "id": 20,
        "tool": "lunarreturn",
        "category": "西洋古典与现代占星",
        "name_zh": "月亮返照推运盘 (Lunar Return)",
        "input": {"date": "2026-09-30", "time": "14:00:00", "target_year": 2026, "month": 10, "lat": 31.23, "lon": 121.47},
        "description": "推算月球每月重返本命黄经时刻构建月运盘",
        "verify_key": "return_moon_lon",
        "check_db": False,
    },
    {
        "id": 21,
        "tool": "lunationphase",
        "category": "西洋古典与现代占星",
        "name_zh": "生辰月相八阶段与生命节律",
        "input": {"date": "2026-09-30", "time": "14:00:00"},
        "description": "日月中天夹角计算新月、上弦、凸月、满月等八形态",
        "verify_key": "phase_name",
        "check_db": False,
    },
    {
        "id": 22,
        "tool": "prenatalsyzygy",
        "category": "西洋古典与现代占星",
        "name_zh": "出生产前朔望合朔点 (Prenatal Syzygy)",
        "input": {"date": "2026-09-30", "time": "14:00:00"},
        "description": "希腊占星计算出生产前最近的新月/满月敏感交点",
        "verify_key": "syzygy_sun_lon",
        "check_db": False,
    },
    {
        "id": 23,
        "tool": "triplicityrulers",
        "category": "西洋古典与现代占星",
        "name_zh": "多罗修斯三分性主星 (Triplicity Rulers)",
        "input": {"date": "2026-09-30", "time": "14:00:00"},
        "description": "古典占星昼夜分得起三主星断一生前中后运",
        "verify_key": "rulers",
        "check_db": False,
    },
    {
        "id": 24,
        "tool": "keypoints",
        "category": "西洋古典与现代占星",
        "name_zh": "阿拉伯点与耶鲁恒星 (BSC5) 相交矩阵",
        "input": {"date": "2026-09-30", "time": "14:00:00", "lat": 31.23, "lon": 121.47},
        "description": "联动 bsc5_stars.bin 8404颗亮星与福点阿拉伯点合相",
        "verify_key": "fixed_star_connections_count",
        "check_db": True,
        "db_field": "fixed_star_connections_count",
    },
    {
        "id": 25,
        "tool": "horary",
        "category": "西洋古典与现代占星",
        "name_zh": "卜卦占星学 (Horary Astrology) 格局判定",
        "input": {"date": "2026-09-30", "time": "14:00:00", "lat": 31.23, "lon": 121.47, "question_type": "career"},
        "description": "问事人第一宫主星与所问事体主星之会合转化裁断",
        "verify_key": "horary_judgment",
        "check_db": False,
    },
    {
        "id": 26,
        "tool": "election",
        "category": "西洋古典与现代占星",
        "name_zh": "西洋择日占星学 (Electional Astrology) 评分",
        "input": {"date": "2026-09-30", "time": "14:00:00", "lat": 31.23, "lon": 121.47},
        "description": "月亮空亡、四轴吉星与凶星受克综合量化打分",
        "verify_key": "void_of_course",
        "check_db": False,
    },
    {
        "id": 27,
        "tool": "babylon",
        "category": "西洋古典与现代占星",
        "name_zh": "巴比伦原始恒星宿度 (Babylonian Zodiac)",
        "input": {"date": "2026-09-30", "time": "14:00:00"},
        "description": "两河流域原始恒星黄道分度与行星入宿",
        "verify_key": "ayanamsa_name",
        "check_db": False,
    },
    {
        "id": 28,
        "tool": "germany",
        "category": "西洋古典与现代占星",
        "name_zh": "汉堡学派乌拉尼亚行星中点与八虚星",
        "input": {"date": "2026-09-30", "time": "14:00:00"},
        "description": "阿佛弗·维特中点占星学与超海王星八天体交角",
        "verify_key": "midpoints",
        "check_db": False,
    },

    # ==========================================
    # 三、东方七政与吠陀印占流派 (6项)
    # ==========================================
    {
        "id": 29,
        "tool": "guolao",
        "category": "七政四余与吠陀印占",
        "name_zh": "琴堂果老星宗七政四余排盘与神煞",
        "input": {"date": "2026-09-30", "time": "14:00:00", "lat": 31.23, "lon": 121.47},
        "description": "日月五星四余（罗睺计都紫炁月孛）入宿度与张果星宗典籍神煞",
        "verify_key": "zhangguo_matrix",
        "check_db": True,
        "db_field": "zhangguo_matrix",
    },
    {
        "id": 30,
        "tool": "qizhengkin",
        "category": "七政四余与吠陀印占",
        "name_zh": "七政四余生克制化与洞微飞星",
        "input": {"date": "2026-09-30", "time": "14:00:00"},
        "description": "洞微大限、政余相生相克与殿驾权衡",
        "verify_key": "seven_governors",
        "check_db": False,
    },
    {
        "id": 31,
        "tool": "vedic",
        "category": "七政四余与吠陀印占",
        "name_zh": "印度吠陀占星 (Vedic D1/D9 九分盘)",
        "input": {"date": "2026-09-30", "time": "14:00:00", "lat": 31.23, "lon": 121.47},
        "description": "恒星黄道拉希里岁差修正、D1 本盘与 D9 纳瓦姆沙分盘",
        "verify_key": "vimshottari_dasha",
        "check_db": False,
    },
    {
        "id": 32,
        "tool": "feigong",
        "category": "七政四余与吠陀印占",
        "name_zh": "吠陀印占飞宫星曜互溶格局",
        "input": {"date": "2026-09-30", "time": "14:00:00", "lat": 31.23, "lon": 121.47},
        "description": "分盘飞星互坐吉凶星格局推衍",
        "verify_key": "palace_stars",
        "check_db": False,
    },
    {
        "id": 33,
        "tool": "india_rectify",
        "category": "七政四余与吠陀印占",
        "name_zh": "印度占星生时微调校正法 (Pranapada/Tattva)",
        "input": {"date": "2026-09-30", "time": "14:00:00", "lat": 31.23, "lon": 121.47},
        "description": "结合生时呼吸刻度与五行微刻反推生时",
        "verify_key": "kp_rectification",
        "check_db": False,
    },
    {
        "id": 34,
        "tool": "relative",
        "category": "七政四余与吠陀印占",
        "name_zh": "六亲衍生分盘推运 (Derived Houses)",
        "input": {"date": "2026-09-30", "time": "14:00:00", "lat": 31.23, "lon": 121.47},
        "description": "以父母/配偶/子女宫立太极推算六亲吉凶",
        "verify_key": "houses",
        "check_db": False,
    },

    # ==========================================
    # 四、高阶星限与推运技术 (19项)
    # ==========================================
    {
        "id": 35,
        "tool": "zr",
        "category": "高阶星限与推运",
        "name_zh": "希腊化黄道释放法 (Zodiacal Releasing)",
        "input": {"date": "2026-09-30", "time": "14:00:00", "age": 28.0},
        "description": "从精神点/福点起算四大释放层级峰值限期",
        "verify_key": "current_period",
        "check_db": False,
    },
    {
        "id": 36,
        "tool": "balbillus",
        "category": "高阶星限与推运",
        "name_zh": "巴比卢斯太阳主限极距推运",
        "input": {"date": "2026-09-30", "time": "14:00:00", "lat": 31.23, "lon": 121.47},
        "description": "古代占星大师巴比卢斯太阳弧赤道极值主限",
        "verify_key": "main_periods",
        "check_db": False,
    },
    {
        "id": 37,
        "tool": "decennials",
        "category": "高阶星限与推运",
        "name_zh": "古典十年限法推运 (Decennials)",
        "input": {"date": "2026-09-30", "time": "14:00:00", "age": 28.0},
        "description": "以生辰昼夜起主导大运星与分步流年副运星",
        "verify_key": "current_period",
        "check_db": False,
    },
    {
        "id": 38,
        "tool": "firdaria",
        "category": "高阶星限与推运",
        "name_zh": "中世纪波斯法达星限法 (Firdaria)",
        "input": {"age": 28.0, "gender": 1},
        "description": "波斯七政与罗睺计都七十五年大循环主副星限",
        "verify_key": "active_lord",
        "check_db": False,
    },
    {
        "id": 39,
        "tool": "distributions",
        "category": "高阶星限与推运",
        "name_zh": "埃及界分布主限推运 (Distributions through Bounds)",
        "input": {"date": "2026-09-30", "time": "14:00:00", "age": 28.0},
        "description": "上升点步进埃及界与参与星形成之大限交替",
        "verify_key": "distributions",
        "check_db": False,
    },
    {
        "id": 40,
        "tool": "persiandirected",
        "category": "高阶星限与推运",
        "name_zh": "波斯流年限星主导法 (Persian Directed System)",
        "input": {"date": "2026-09-30", "time": "14:00:00", "age": 28.0},
        "description": "波斯传统九曜轮转度数限主与年主星",
        "verify_key": "directed_ruler",
        "check_db": False,
    },
    {
        "id": 41,
        "tool": "planetaryages",
        "category": "高阶星限与推运",
        "name_zh": "行星生命周期论 (Planetary Ages of Man)",
        "input": {"age": 28.0},
        "description": "月亮掌幼、水星掌少、金星掌青等人生各阶段七政管辖",
        "verify_key": "active_planet",
        "check_db": False,
    },
    {
        "id": 42,
        "tool": "yearsystem129",
        "category": "高阶星限与推运",
        "name_zh": "瓦伦斯 129 年周天限法 (Valens 129-Year System)",
        "input": {"date": "2026-09-30", "time": "14:00:00", "age": 28.0},
        "description": "古典占星家瓦伦斯命理全息数理周期",
        "verify_key": "main_ruler",
        "check_db": False,
    },
    {
        "id": 43,
        "tool": "profection",
        "category": "高阶星限与推运",
        "name_zh": "古典希腊小限法 (Annual Profections)",
        "input": {"age": 28.0},
        "description": "以每年移一宫原则判定该年主宰星座与年限主星",
        "verify_key": "profection_house",
        "check_db": False,
    },
    {
        "id": 44,
        "tool": "draconic",
        "category": "高阶星限与推运",
        "name_zh": "龙首交点盘 (Draconic Chart / 灵魂盘)",
        "input": {"date": "2026-09-30", "time": "14:00:00", "lat": 31.23, "lon": 121.47},
        "description": "将北交点归零重排全盘揭示前世灵魂印记",
        "verify_key": "planets",
        "check_db": False,
    },
    {
        "id": 45,
        "tool": "solararc",
        "category": "高阶星限与推运",
        "name_zh": "太阳弧推运法 (Solar Arc Directions)",
        "input": {"date": "2026-09-30", "time": "14:00:00", "target_date": "2030-01-01"},
        "description": "按目标日太阳真实行进步进全盘所有天体",
        "verify_key": "arc_degree",
        "check_db": False,
    },
    {
        "id": 46,
        "tool": "harmonic",
        "category": "高阶星限与推运",
        "name_zh": "高阶谐波占星分析 (Harmonic Chart)",
        "input": {"date": "2026-09-30", "time": "14:00:00", "harmonic": 7.0},
        "description": "指定谐波阶次展开揭示特殊心理天赋与灵性",
        "verify_key": "planets",
        "check_db": False,
    },
    {
        "id": 47,
        "tool": "pd",
        "category": "高阶星限与推运",
        "name_zh": "主限推运半弧赤道直升法 (Primary Directions)",
        "input": {"date": "2026-09-30", "time": "14:00:00", "lat": 31.23, "lon": 121.47, "age": 28.0},
        "description": "普拉西德赤道斜升与子午半弧高精主限",
        "verify_key": "hits",
        "check_db": False,
    },
    {
        "id": 48,
        "tool": "mundane",
        "category": "高阶星限与推运",
        "name_zh": "世俗占星白羊春分入宫盘 (Aries Ingress)",
        "input": {"year": 2026, "lon": 121.47, "lat": 31.23},
        "description": "推算太阳进入白羊座0度世俗国运春分盘",
        "verify_key": "primary_ingress",
        "check_db": False,
    },
    {
        "id": 49,
        "tool": "ephemeris",
        "category": "高阶星限与推运",
        "name_zh": "现代高精瑞士物理星历切片自检 (SEPK)",
        "input": {"date": "2026-09-30", "time": "14:00:00"},
        "description": "自检核心切比雪夫切片与小行星数据流",
        "verify_key": "sepk_baked_slices_count",
        "check_db": True,
        "db_field": "sepk_baked_slices_count",
    },
    {
        "id": 50,
        "tool": "planet_cycles",
        "category": "高阶星限与推运",
        "name_zh": "外行星周期与世界历史周期律 (Planetary Cycles)",
        "input": {"date": "2026-09-30", "time": "14:00:00"},
        "description": "木土合相、土天周期与时代宏观趋势",
        "verify_key": "planets",
        "check_db": False,
    },
    {
        "id": 51,
        "tool": "returntimeline",
        "category": "高阶星限与推运",
        "name_zh": "返照周期连续时间线 (Return Timeline)",
        "input": {"date": "2026-09-30", "time": "14:00:00", "start_year": 2026, "end_year": 2030},
        "description": "跨年度连续太阳返照盘演变脉络",
        "verify_key": "timeline",
        "check_db": False,
    },
    {
        "id": 52,
        "tool": "extrareturns",
        "category": "高阶星限与推运",
        "name_zh": "火星金星木星各大行星扩展返照",
        "input": {"date": "2026-09-30", "time": "14:00:00"},
        "description": "金星返照盘与火星返照盘专项推运",
        "verify_key": "returns",
        "check_db": False,
    },
    {
        "id": 53,
        "tool": "agepoint",
        "category": "高阶星限与推运",
        "name_zh": "胡伯学派年龄点推运 (Huber Life Clock)",
        "input": {"date": "2026-09-30", "time": "14:00:00", "age": 28.0},
        "description": "每六年换一宫位人生时钟深度心理分析",
        "verify_key": "age_point_degree",
        "check_db": False,
    },
    {
        "id": 54,
        "tool": "planetaryarc",
        "category": "高阶星限与推运",
        "name_zh": "各大行星物理弧长推运 (Planetary Arc)",
        "input": {"date": "2026-09-30", "time": "14:00:00", "age": 28.0},
        "description": "木星弧、土星弧与火星弧专门事体推运",
        "verify_key": "arc_degrees",
        "check_db": False,
    },
    {
        "id": 55,
        "tool": "jaynesprog",
        "category": "高阶星限与推运",
        "name_zh": "查尔斯·简恩综合次限进阶推进 (Jayne's Progression)",
        "input": {"date": "2026-09-30", "time": "14:00:00", "age": 28.0},
        "description": "次限一日一年结合三限一周一月综合论断",
        "verify_key": "progressed_planets",
        "check_db": False,
    },
    {
        "id": 56,
        "tool": "vedicprog",
        "category": "高阶星限与推运",
        "name_zh": "吠陀 Vimshottari 维姆绍塔里大限双向推进",
        "input": {"date": "2026-09-30", "time": "14:00:00", "age": 28.0},
        "description": "120年星宿大限(Maha Dasha)与副限(Antar Dasha)",
        "verify_key": "dasha_periods",
        "check_db": False,
    },
    {
        "id": 57,
        "tool": "givenyear",
        "category": "高阶星限与推运",
        "name_zh": "指定目标流年综合占星快照",
        "input": {"date": "2026-09-30", "time": "14:00:00", "target_year": 2028},
        "description": "集成返照、小限与主限之流年全景",
        "verify_key": "progressed_jde",
        "check_db": False,
    },
    {
        "id": 58,
        "tool": "hellen_chart",
        "category": "高阶星限与推运",
        "name_zh": "希腊化整宫制本命盘与多罗修斯界律",
        "input": {"date": "2026-09-30", "time": "14:00:00", "lat": 31.23, "lon": 121.47},
        "description": "古典希腊整宫制（Whole Sign Houses）与埃及界分布",
        "verify_key": "egyptian_bounds",
        "check_db": False,
    },

    # ==========================================
    # 五、易经卦象与数术秘典 (7项)
    # ==========================================
    {
        "id": 59,
        "tool": "liuyao",
        "category": "易经卦象与数术",
        "name_zh": "周易纳甲六爻梅花起卦",
        "input": {"numbers": [1, 5, 3]},
        "description": "以数起卦、定上下本卦、安世应、六亲与动爻变卦",
        "verify_key": "original_gua",
        "check_db": False,
    },
    {
        "id": 60,
        "tool": "gua_desc",
        "category": "易经卦象与数术",
        "name_zh": "六十四卦卦名彖传深度详解",
        "input": {"numbers": [7, 8, 2]},
        "description": "卦象吉凶、象传彖传与易理释义",
        "verify_key": "original_gua",
        "check_db": False,
    },
    {
        "id": 61,
        "tool": "gua_meiyi",
        "category": "易经卦象与数术",
        "name_zh": "梅花易数体用生克决断",
        "input": {"numbers": [3, 2, 4]},
        "description": "定体卦用卦、互卦变卦五行生克定吉凶成败",
        "verify_key": "original_gua",
        "check_db": False,
    },
    {
        "id": 62,
        "tool": "heluo",
        "category": "易经卦象与数术",
        "name_zh": "河洛理数天地数与先后天卦典籍诗赋",
        "input": {"date": "2026-09-30", "time": "14:00:00", "gender": 1},
        "description": "天数二十五、地数三十生成先后天卦，命中 tiaowen.bin 原典",
        "verify_key": "heluo_canon_verse",
        "check_db": True,
        "db_field": "heluo_canon_verse",
    },
    {
        "id": 63,
        "tool": "canping",
        "category": "易经卦象与数术",
        "name_zh": "邵子参评数五行日宫命宫大运",
        "input": {"date": "2026-09-30", "time": "14:00:00"},
        "description": "顺数逆数演大运，深度联动 tiaowen.bin canping_verses",
        "verify_key": "canping_canon_data",
        "check_db": True,
        "db_field": "canping_canon_data",
    },
    {
        "id": 64,
        "tool": "shaozi",
        "category": "易经卦象与数术",
        "name_zh": "邵子神数六千一百四十四数原典条文",
        "input": {"year_gz": "丙午", "month_gz": "丁酉", "day_gz": "丁未", "hour_gz": "丁未"},
        "description": "四柱天干地支数理推演，命中 tiaowen.bin shaozi_verses 真实条文",
        "verify_key": "verse_text",
        "check_db": True,
        "db_field": "verse_text",
    },
    {
        "id": 65,
        "tool": "tieban",
        "category": "易经卦象与数术",
        "name_zh": "铁板神数一万二千条文秘数推导",
        "input": {"date": "2026-09-30", "time": "14:00:00"},
        "description": "先天数、后天数、日命数推演，命中 tiaowen.bin tieban_verses 真实条文",
        "verify_key": "verse_text",
        "check_db": True,
        "db_field": "verse_text",
    },

    # ==========================================
    # 六、十大神数典籍家族 (11项)
    # ==========================================
    {
        "id": 66,
        "tool": "shenshu",
        "category": "十大神数典籍",
        "name_zh": "皇极观物演义神数",
        "input": {"family_key": "nanji", "year_gz": "丙午", "month_gz": "丁酉", "day_gz": "丁未", "hour_gz": "丁未"},
        "description": "通用神数家族矩阵分发调度",
        "verify_key": "verse_text",
        "check_db": True,
        "db_field": "verse_text",
    },
    {
        "id": 67,
        "tool": "nanji",
        "category": "十大神数典籍",
        "name_zh": "南极神数秘典条文",
        "input": {"year_gz": "丙午", "month_gz": "丁酉", "day_gz": "丁未", "hour_gz": "丁未"},
        "description": "南极星君演化二百四十六数秘典条文",
        "verify_key": "verse_text",
        "check_db": True,
        "db_field": "verse_text",
    },
    {
        "id": 68,
        "tool": "beiji",
        "category": "十大神数典籍",
        "name_zh": "北极神数正统卦数条文",
        "input": {"year_gz": "丙午", "month_gz": "丁酉", "day_gz": "丁未", "hour_gz": "丁未"},
        "description": "北极玄枢二千三百四十一数条文",
        "verify_key": "verse_text",
        "check_db": True,
        "db_field": "verse_text",
    },
    {
        "id": 69,
        "tool": "taixuan",
        "category": "十大神数典籍",
        "name_zh": "太玄经八十一首太玄诗法",
        "input": {"year_gz": "丙午", "month_gz": "丁酉", "day_gz": "丁未", "hour_gz": "丁未"},
        "description": "扬雄太玄三方九州二十七部八十一首原典诗赋",
        "verify_key": "verse_text",
        "check_db": True,
        "db_field": "verse_text",
    },
    {
        "id": 70,
        "tool": "wangji",
        "category": "十大神数典籍",
        "name_zh": "心易发微皇极四象望蓟数",
        "input": {"year_gz": "丙午", "month_gz": "丁酉", "day_gz": "丁未", "hour_gz": "丁未"},
        "description": "心易发微秘传四象望蓟数理",
        "verify_key": "verse_text",
        "check_db": True,
        "db_field": "verse_text",
    },
    {
        "id": 71,
        "tool": "cetian",
        "category": "十大神数典籍",
        "name_zh": "策天神数大衍策数",
        "input": {"year_gz": "丙午", "month_gz": "丁酉", "day_gz": "丁未", "hour_gz": "丁未"},
        "description": "大衍之数五十策天推命法",
        "verify_key": "verse_text",
        "check_db": True,
        "db_field": "verse_text",
    },
    {
        "id": 72,
        "tool": "chunzi",
        "category": "十大神数典籍",
        "name_zh": "蠢子神数四千五百七十五数",
        "input": {"year_gz": "丙午", "month_gz": "丁酉", "day_gz": "丁未", "hour_gz": "丁未"},
        "description": "蠢子神数原典四千余数命运批注",
        "verify_key": "verse_text",
        "check_db": True,
        "db_field": "verse_text",
    },
    {
        "id": 73,
        "tool": "fendjing",
        "category": "十大神数典籍",
        "name_zh": "分经神数易理分经数",
        "input": {"year_gz": "丙午", "month_gz": "丁酉", "day_gz": "丁未", "hour_gz": "丁未"},
        "description": "八卦分经六十四卦经文推断",
        "verify_key": "verse_text",
        "check_db": True,
        "db_field": "verse_text",
    },
    {
        "id": 74,
        "tool": "jingjue",
        "category": "十大神数典籍",
        "name_zh": "警觉神数醒世吉凶秘数",
        "input": {"year_gz": "丙午", "month_gz": "丁酉", "day_gz": "丁未", "hour_gz": "丁未"},
        "description": "醒世警觉秘数断吉凶悔吝",
        "verify_key": "verse_text",
        "check_db": True,
        "db_field": "verse_text",
    },
    {
        "id": 75,
        "tool": "shenyishu",
        "category": "十大神数典籍",
        "name_zh": "神易数易数心法",
        "input": {"year_gz": "丙午", "month_gz": "丁酉", "day_gz": "丁未", "hour_gz": "丁未"},
        "description": "神易四柱五行干支纳音秘断",
        "verify_key": "verse_text",
        "check_db": True,
        "db_field": "verse_text",
    },
    {
        "id": 76,
        "tool": "wuzhao",
        "category": "十大神数典籍",
        "name_zh": "五兆神数先知吉凶秘数",
        "input": {"year_gz": "丙午", "month_gz": "丁酉", "day_gz": "丁未", "hour_gz": "丁未"},
        "description": "五兆先机观兆演数断法",
        "verify_key": "verse_text",
        "check_db": True,
        "db_field": "verse_text",
    },

    # ==========================================
    # 七、通胜老黄历与全域择吉体系 (12项)
    # ==========================================
    {
        "id": 77,
        "tool": "tongshu",
        "category": "通胜择吉与历法",
        "name_zh": "通胜老黄历建除十二神廿八宿",
        "input": {"date": "2026-09-30"},
        "description": "建除十二客神、廿八宿与黄黑道神煞",
        "verify_key": "xiu28_star",
        "check_db": False,
    },
    {
        "id": 78,
        "tool": "bazizeri",
        "category": "通胜择吉与历法",
        "name_zh": "八字五行生克吉时扫描",
        "input": {"start_date": "2026-10-01", "end_date": "2026-10-02"},
        "description": "区间遍历时辰筛选干支生克印比得禄之吉时",
        "verify_key": "hits_count",
        "check_db": False,
    },
    {
        "id": 79,
        "tool": "qimenzeri",
        "category": "通胜择吉与历法",
        "name_zh": "奇门遁甲三吉门得奇择时扫描",
        "input": {"start_date": "2026-10-01", "end_date": "2026-10-02"},
        "description": "扫描开休生三吉门临三奇之大吉时辰",
        "verify_key": "hits_count",
        "check_db": False,
    },
    {
        "id": 80,
        "tool": "taiyizeri",
        "category": "通胜择吉与历法",
        "name_zh": "太乙神数天目客大将得位择日",
        "input": {"start_date": "2026-10-01", "end_date": "2026-10-02"},
        "description": "太乙天目与客大将、主大将生旺不犯囚迫之吉日",
        "verify_key": "hits_count",
        "check_db": False,
    },
    {
        "id": 81,
        "tool": "ziweizeri",
        "category": "通胜择吉与历法",
        "name_zh": "紫微斗数三方四正吉曜加临择日",
        "input": {"start_date": "2026-10-01", "end_date": "2026-10-02"},
        "description": "紫微紫府天相三台八座吉曜临宫择吉",
        "verify_key": "hits_count",
        "check_db": False,
    },
    {
        "id": 82,
        "tool": "liurengzeri",
        "category": "通胜择吉与历法",
        "name_zh": "大六壬三传吉将吉神汇聚择吉",
        "input": {"start_date": "2026-10-01", "end_date": "2026-10-02"},
        "description": "三传初传青龙贵人太常吉神发用择吉",
        "verify_key": "hits_count",
        "check_db": False,
    },
    {
        "id": 83,
        "tool": "sanshizeri",
        "category": "通胜择吉与历法",
        "name_zh": "三式合一同契天地大成择日",
        "input": {"start_date": "2026-10-01", "end_date": "2026-10-02"},
        "description": "太乙奇门六壬三式共振上吉良辰扫描",
        "verify_key": "hits_count",
        "check_db": False,
    },
    {
        "id": 84,
        "tool": "qizhengzeri",
        "category": "通胜择吉与历法",
        "name_zh": "七政四余日月拱照天星择日",
        "input": {"start_date": "2026-10-01", "end_date": "2026-10-02"},
        "description": "日月拱照四正天星贵格择日",
        "verify_key": "hits_count",
        "check_db": False,
    },
    {
        "id": 85,
        "tool": "indiazeri",
        "category": "通胜择吉与历法",
        "name_zh": "吠陀印度占星纳克夏特拉择日 (Muhurta)",
        "input": {"start_date": "2026-10-01", "end_date": "2026-10-02"},
        "description": "月宿吉祥 Nakshatra 与 Tithi 时位择吉",
        "verify_key": "hits_count",
        "check_db": False,
    },
    {
        "id": 86,
        "tool": "huanglizeri",
        "category": "通胜择吉与历法",
        "name_zh": "通书黄历黄道吉日神煞避凶",
        "input": {"start_date": "2026-10-01", "end_date": "2026-10-02"},
        "description": "青龙明堂金匮天德吉神值日筛选",
        "verify_key": "hits_count",
        "check_db": False,
    },
    {
        "id": 87,
        "tool": "zeri",
        "category": "通胜择吉与历法",
        "name_zh": "通用多维条件良辰扫描器",
        "input": {"start_date": "2026-10-01", "end_date": "2026-10-02"},
        "description": "支持门向、吉星、干支自定义复合条件过滤",
        "verify_key": "hits_count",
        "check_db": False,
    },
    {
        "id": 88,
        "tool": "qizhengelection",
        "category": "通胜择吉与历法",
        "name_zh": "琴堂七政星曜入度天机择吉",
        "input": {"start_date": "2026-10-01", "end_date": "2026-10-02"},
        "description": "琴堂星宗科名科甲星临四轴择吉",
        "verify_key": "hits_count",
        "check_db": False,
    },

    # ==========================================
    # 八、民间杂占与西方神秘学 (11项)
    # ==========================================
    {
        "id": 89,
        "tool": "xiaoliuren",
        "category": "民间杂占与西方神秘学",
        "name_zh": "小六壬六神流转断事",
        "input": {"month": 9, "day": 30, "hour": 14},
        "description": "大安、留连、速喜、赤口、小吉、空亡六神掐指推断",
        "verify_key": "mo_chuan",
        "check_db": False,
    },
    {
        "id": 90,
        "tool": "yizhangjing",
        "category": "民间杂占与西方神秘学",
        "name_zh": "达摩一掌经佛道儒鬼四柱轮转",
        "input": {"month": 9, "day": 30, "hour": 14},
        "description": "佛道儒鬼十二星宿轮转，深度联动 tiaowen.bin 典籍",
        "verify_key": "damo_data_canonical",
        "check_db": True,
        "db_field": "damo_data_canonical",
    },
    {
        "id": 91,
        "tool": "lingqi",
        "category": "民间杂占与西方神秘学",
        "name_zh": "汉代灵棋经上中下子成卦演辞",
        "input": {"numbers": [1, 2, 0]},
        "description": "十二棋子成卦，天上下十二卦象断辞",
        "verify_key": "poem",
        "check_db": False,
    },
    {
        "id": 92,
        "tool": "tarot",
        "category": "民间杂占与西方神秘学",
        "name_zh": "西方塔罗牌78张洗牌与三牌阵牌义",
        "input": {"spread": "three_cards", "seed": 42},
        "description": "大阿卡那小阿卡那洗牌、正逆位判定，联动 tiaowen.bin 牌义与卡巴拉元素对应",
        "verify_key": "drawn_cards",
        "check_db": True,
        "db_field": "tarot_element_correspondence",
    },
    {
        "id": 93,
        "tool": "geomancy",
        "category": "民间杂占与西方神秘学",
        "name_zh": "大地占卜泥土点十六卦天文地占",
        "input": {"numbers": [1, 2, 1, 2]},
        "description": "十六地占图形生成四大母亲卦、法官卦与左右证人",
        "verify_key": "judge",
        "check_db": False,
    },
    {
        "id": 94,
        "tool": "guice",
        "category": "民间杂占与西方神秘学",
        "name_zh": "鬼谷子分定经两头钳命局诗断",
        "input": {"year_gz": "丙午", "hour_gz": "丁未"},
        "description": "以年干时干两头钳配生平格调诗词",
        "verify_key": "base_poem",
        "check_db": False,
    },
    {
        "id": 95,
        "tool": "tongshefa",
        "category": "民间杂占与西方神秘学",
        "name_zh": "古通社法四象推演断法",
        "input": {"numbers": [1, 2, 1, 2]},
        "description": "太阳太阴少阳少阴四象演化断法",
        "verify_key": "main_relation",
        "check_db": False,
    },
    {
        "id": 96,
        "tool": "yanqin",
        "category": "民间杂占与西方神秘学",
        "name_zh": "演禽神数二十八宿翻禽倒将",
        "input": {"year_gz": "丙午", "month_gz": "丁酉", "day_gz": "丁未", "hour_gz": "丁未"},
        "description": "七元甲子禽星值日值时与翻禽倒将生克",
        "verify_key": "fan_qin",
        "check_db": False,
    },
    {
        "id": 97,
        "tool": "xianqin",
        "category": "民间杂占与西方神秘学",
        "name_zh": "禽星六十花甲值宿命理",
        "input": {"year_gz": "丙午", "hour_gz": "丁未"},
        "description": "六十甲子配二十八宿禽星命理断词",
        "verify_key": "fan_qin",
        "check_db": False,
    },
    {
        "id": 98,
        "tool": "suzhan",
        "category": "民间杂占与西方神秘学",
        "name_zh": "宿占正传二十八宿值日断吉凶",
        "input": {"month": 9, "day": 30},
        "description": "宿占正传以月日干支起宿断出行百事",
        "verify_key": "day_mansion",
        "check_db": False,
    },
    {
        "id": 99,
        "tool": "otherbu",
        "category": "民间杂占与西方神秘学",
        "name_zh": "太公太玄金钱课杂占诸法",
        "input": {"spread": "coin", "seed": 888},
        "description": "太公金钱课掷钱起卦占验法",
        "verify_key": "hexagram_name",
        "check_db": False,
    },

    # ==========================================
    # 九、天星外步、小成图与宏观知识库 (11项)
    # ==========================================
    {
        "id": 100,
        "tool": "tianxing",
        "category": "天星小成图与知识库",
        "name_zh": "天星五星聚舍交角吉凶断法",
        "input": {"date": "2026-09-30", "time": "14:00:00"},
        "description": "金木水火土五星聚舍与恒星交会天象吉凶",
        "verify_key": "hits",
        "check_db": False,
    },
    {
        "id": 101,
        "tool": "tianxingzeri",
        "category": "天星小成图与知识库",
        "name_zh": "天星外步选择吉度吉时",
        "input": {"date": "2026-09-30", "time": "14:00:00"},
        "description": "天星过宫外步度数择吉算法",
        "verify_key": "hits",
        "check_db": False,
    },
    {
        "id": 102,
        "tool": "xiaochengtu",
        "category": "天星小成图与知识库",
        "name_zh": "霍斐然小成图九宫归藏天地排盘",
        "input": {"up": "乾", "lo": "坤"},
        "description": "霍斐然小成图归藏易理入九宫排布",
        "verify_key": "gong_palaces",
        "check_db": False,
    },
    {
        "id": 103,
        "tool": "xuanshi",
        "category": "天星小成图与知识库",
        "name_zh": "二十四史历代天象志与玄学历史事件库",
        "input": {"name": "李淳风"},
        "description": "内核级 MMap 零拷贝检索 xuanshi.bin 历代正史天象",
        "verify_key": "summary",
        "check_db": True,
        "db_field": "hits_count",
    },
    {
        "id": 104,
        "tool": "astrodata",
        "category": "天星小成图与知识库",
        "name_zh": "全球近6万名流占星案例库 (AstroDataBank)",
        "input": {"name": "Einstein"},
        "description": "LZMA 高压缩二进制案例库 astrodata_cases.bin 检索",
        "verify_key": "total_records",
        "check_db": True,
        "db_field": "hits",
    },
    {
        "id": 105,
        "tool": "export_registry",
        "category": "天星小成图与知识库",
        "name_zh": "全量110技法输出协议与格式快照注册表",
        "input": {"format": "json"},
        "description": "注册表与格式化快照协议规范导出",
        "verify_key": "total_techniques",
        "check_db": False,
    },
    {
        "id": 106,
        "tool": "knowledge_registry",
        "category": "天星小成图与知识库",
        "name_zh": "老吴大师全谱系典籍元数据总索引",
        "input": {"domain": "all"},
        "description": "18套古籍词典与二进制数据库结构目录元数据",
        "verify_key": "citations",
        "check_db": False,
    },
    {
        "id": 107,
        "tool": "nongli_time",
        "category": "天星小成图与知识库",
        "name_zh": "真太阳时经纬度自动折算 (CGEO 联动)",
        "input": {"date": "2026-09-30", "time": "14:00:00", "city": "北京"},
        "description": "联动 china_geo.bin 全国地名自动解析真太阳时时差",
        "verify_key": "location",
        "check_db": True,
        "db_field": "location",
    },
    {
        "id": 108,
        "tool": "jieqi_birth",
        "category": "天星小成图与知识库",
        "name_zh": "秒级平黄经交节节气分界算法",
        "input": {"date": "2026-09-30", "time": "14:00:00"},
        "description": "精确推算上一节气与下一节气之精确时刻与黄经",
        "verify_key": "current_jieqi",
        "check_db": False,
    },
    {
        "id": 109,
        "tool": "jieqi_year",
        "category": "天星小成图与知识库",
        "name_zh": "全公历年二十四节气公历时刻精密时刻表",
        "input": {"year": 2026},
        "description": "生成指定年份全部24节气精确儒略日与公历时刻",
        "verify_key": "annual_jieqi_schedule",
        "check_db": False,
    },
    {
        "id": 110,
        "tool": "calendar_month",
        "category": "天星小成图与知识库",
        "name_zh": "万年历公农历干支交节与月相矩阵",
        "input": {"year": 2026, "month": 10},
        "description": "整月公历、农历、干支、建除、节气一体化日历表",
        "verify_key": "calendar_days",
        "check_db": False,
    },
]
